apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-rtfu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-rtfu
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-rtfu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-rtfu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-rtfu
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-uvnr-tenant/dotnet-component/devfile-sample-dotnet60-basic-rtfu@sha256:4eeb00bdac26c681471864fb287698e40c129e558101d1ae1b5689ccebf83803
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
